### ISSUE TITLE
Unable to launch kubernetes system stack.

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher-catalog#159]
Here is the stack trace:

6/13/2016 5:03:08 PMgoroutine 51 [running]:
6/13/2016 5:03:08 PMpanic(0xbeaf00, 0xc8202b6f10)
6/13/2016 5:03:08 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/13/2016 5:03:08 PMgithub.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc820192020, 0x10de7a0, 0x5d, 0xc820314ac0, 0x2, 0x2)
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x191
6/13/2016 5:03:08 PMgithub.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8201a08c0, 0x78)
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
6/13/2016 5:03:08 PMgithub.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc8200ac300, 0x8, 0x280351b808a325d8, 0x4c531b5bcd6a0ff5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
6/13/2016 5:03:08 PMgithub.com/coreos/etcd/raft.stepFollower(0xc8200ac300, 0x8, 0x280351b808a325d8, 0x4c531b5bcd6a0ff5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
6/13/2016 5:03:08 PMgithub.com/coreos/etcd/raft.(*raft).Step(0xc8200ac300, 0x8, 0x280351b808a325d8, 0x4c531b5bcd6a0ff5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
6/13/2016 5:03:08 PMgithub.com/coreos/etcd/raft.(*node).run(0xc820179130, 0xc8200ac300)
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
6/13/2016 5:03:08 PMcreated by github.com/coreos/etcd/raft.RestartNode
6/13/2016 5:03:08 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4

**Comment by leodotcloud** [comment]
https://github.com/rancher/rancher/issues/5103
